### ISSUE TITLE
Audio Player on UITableViewCell

### ISSUE THREAD

**Issue by hardikamal** [seroshtanov/miniPlayer#1]
Hi @seroshtanov 
First of all thanks for the awesome mini player.

I have one query ie. I am using this player on the table view cell. It works perfectly. The only issue is when I play the next audio the previous one does not pause/stop. How do I achieve that?

**Comment by seroshtanov** [comment]
Hi! 
Thanks for using mimi player.
Unfortunately, it feature hasn’t done yet.

One of ways achieve it - using NotificationCenter.

For example: 
In UItableViewCell subclass: 

private var fileId : Int!

static let startPlayNotification = NSNotification.Name.init(rawValue: "com.bundleid.AudioCell.startPlayNotification»)

override func awakeFromNib() {
        super.awakeFromNib()
        NotificationCenter.default.addObserver(self, selector: #selector(stopPlayNotification(object:)), 	
							 name: AudioCell.startPlayNotification, object: nil)
}

@objc fileprivate func stopPlayNotification(object: Notification) {
    if let hash = object.userInfo?["hash"] as? Int, hash != fileId {
        print("Stopped hash: \(hashValue)")
        self.player.stop()
    }
}

deinit {
    NotificationCenter.default.removeObserver(self)
}


extension AudioCell: MiniPlayerDelegate{
    func didPlay(player: MiniPlayer) {
        NotificationCenter.default.post(name: AudioCell.startPlayNotification, object: nil, userInfo: ["hash": fileId!])
    }
    
    func didStop(player: MiniPlayer) {}
    
    func didPause(player: MiniPlayer) {}
    
}


Hope it helps!

**Comment by hardikamal** [comment]
@seroshtanov Bro this worked. Thanks a lot.
